<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PrintSaaS.Models\PrintSaaS.Models.csproj" />
    <ProjectReference Include="..\PrintSaaS.Core\PrintSaaS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NRules" Version="1.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
