// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintSaaS.Data;

#nullable disable

namespace PrintSaaS.Data.Migrations
{
    [DbContext(typeof(PrintContext))]
    [Migration("20260317055141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrintSaaS.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ComplianceNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("PrintSaaS.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("PrinterJobId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("QueueProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("QueueProfileId");

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PrintSaaS.Models.JobHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OperatorId");

                    b.ToTable("JobHistories");
                });

            modelBuilder.Entity("PrintSaaS.Models.JobParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ContainsCheques")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsStubs")
                        .HasColumnType("bit");

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDuplex")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayrollJob")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("PagesPerEmployee")
                        .HasColumnType("int");

                    b.Property<string>("PaperType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalPageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("JobParameters");
                });

            modelBuilder.Entity("PrintSaaS.Models.MachineQueueName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("MachineQueueNames");
                });

            modelBuilder.Entity("PrintSaaS.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCapability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DefaultQueueName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCapability = "BW",
                            DefaultQueueName = "Nuvera",
                            IpAddress = "192.168.1.101",
                            IsActive = true,
                            IsOnline = false,
                            Model = "Xerox Nuvera 144MX",
                            Name = "Nuvera 144MX",
                            Port = 443,
                            Protocol = "IPPS"
                        },
                        new
                        {
                            Id = 2,
                            ColorCapability = "Color",
                            DefaultQueueName = "Brenva",
                            IpAddress = "192.168.1.102",
                            IsActive = true,
                            IsOnline = false,
                            Model = "Xerox Brenva HD",
                            Name = "Brenva HD",
                            Port = 443,
                            Protocol = "IPPS"
                        },
                        new
                        {
                            Id = 3,
                            ColorCapability = "Both",
                            DefaultQueueName = "Iridesse",
                            IpAddress = "192.168.1.103",
                            IsActive = true,
                            IsOnline = false,
                            Model = "Xerox Iridesse",
                            Name = "Iridesse",
                            Port = 443,
                            Protocol = "IPPS"
                        });
                });

            modelBuilder.Entity("PrintSaaS.Models.QueueProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HoldOnArrival")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDuplex")
                        .HasColumnType("bit");

                    b.Property<string>("MachineQueueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("TrayProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("TrayProfileId");

                    b.ToTable("QueueProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorMode = "BW",
                            DisplayName = "PDF Duplex B&W",
                            HoldOnArrival = false,
                            IsActive = true,
                            IsDuplex = true,
                            MachineQueueName = "Duplex-BW-Letter",
                            PrinterId = 1,
                            Priority = 1,
                            TrayProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorMode = "BW",
                            DisplayName = "PDF Simplex B&W",
                            HoldOnArrival = false,
                            IsActive = true,
                            IsDuplex = false,
                            MachineQueueName = "Simplex-BW-Letter",
                            PrinterId = 1,
                            Priority = 2,
                            TrayProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            ColorMode = "BW",
                            DisplayName = "Cheque Run",
                            HoldOnArrival = false,
                            IsActive = true,
                            IsDuplex = true,
                            MachineQueueName = "Cheque-Duplex",
                            PrinterId = 1,
                            Priority = 1,
                            TrayProfileId = 2
                        },
                        new
                        {
                            Id = 4,
                            ColorMode = "Color",
                            DisplayName = "Color Duplex",
                            HoldOnArrival = false,
                            IsActive = true,
                            IsDuplex = true,
                            MachineQueueName = "Color-Duplex-Letter",
                            PrinterId = 2,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("PrintSaaS.Models.TrayProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PaperSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaperType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaperWeight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<int>("TrayNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("TrayProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PaperSize = "Letter",
                            PaperType = "Plain",
                            PaperWeight = "75gsm",
                            PrinterId = 1,
                            TrayNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PaperSize = "Letter",
                            PaperType = "Bond",
                            PaperWeight = "90gsm",
                            PrinterId = 1,
                            TrayNumber = 2
                        });
                });

            modelBuilder.Entity("PrintSaaS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Administrateur",
                            IsActive = true,
                            PasswordHash = "$2a$11$placeholder_will_be_set_at_runtime",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PrintSaaS.Models.AuditEntry", b =>
                {
                    b.HasOne("PrintSaaS.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrintSaaS.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("PrintSaaS.Models.Job", b =>
                {
                    b.HasOne("PrintSaaS.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("PrintSaaS.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId");

                    b.HasOne("PrintSaaS.Models.QueueProfile", "QueueProfile")
                        .WithMany()
                        .HasForeignKey("QueueProfileId");

                    b.Navigation("Operator");

                    b.Navigation("Printer");

                    b.Navigation("QueueProfile");
                });

            modelBuilder.Entity("PrintSaaS.Models.JobHistory", b =>
                {
                    b.HasOne("PrintSaaS.Models.Job", "Job")
                        .WithMany("History")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintSaaS.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.Navigation("Job");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("PrintSaaS.Models.JobParameters", b =>
                {
                    b.HasOne("PrintSaaS.Models.Job", "Job")
                        .WithOne("Parameters")
                        .HasForeignKey("PrintSaaS.Models.JobParameters", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PrintSaaS.Models.MachineQueueName", b =>
                {
                    b.HasOne("PrintSaaS.Models.Printer", "Printer")
                        .WithMany("MachineQueueNames")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintSaaS.Models.QueueProfile", b =>
                {
                    b.HasOne("PrintSaaS.Models.Printer", "Printer")
                        .WithMany("QueueProfiles")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintSaaS.Models.TrayProfile", "TrayProfile")
                        .WithMany()
                        .HasForeignKey("TrayProfileId");

                    b.Navigation("Printer");

                    b.Navigation("TrayProfile");
                });

            modelBuilder.Entity("PrintSaaS.Models.TrayProfile", b =>
                {
                    b.HasOne("PrintSaaS.Models.Printer", "Printer")
                        .WithMany("TrayProfiles")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintSaaS.Models.Job", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("PrintSaaS.Models.Printer", b =>
                {
                    b.Navigation("MachineQueueNames");

                    b.Navigation("QueueProfiles");

                    b.Navigation("TrayProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
