<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PrintSaaS.Models\PrintSaaS.Models.csproj" />
    <ProjectReference Include="..\PrintSaaS.Core\PrintSaaS.Core.csproj" />
    <ProjectReference Include="..\PrintSaaS.Data\PrintSaaS.Data.csproj" />
    <ProjectReference Include="..\PrintSaaS.Rules\PrintSaaS.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="SharpIpp" Version="0.10.0" />
    <PackageReference Include="SnmpSharpNet" Version="0.9.7" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
